from linguas.models import Autor
from django.contrib import admin

admin.site.register(Autor)
admin.site.register(Programa)
admin.site.register(RedeTrabalho)
admin.site.register(Programa)
admin.site.register(Idioma)
admin.site.register(Local)
admin.site.register(Keyword)
admin.site.register(Natureza)
admin.site.register(Usuario)
admin.site.register(RedeUsuario)
admin.site.register(Comentario)
admin.site.register(Documento)
admin.site.register(Descricao)
admin.site.register(DocumentoKeyword)
admin.site.register(Favorito)
admin.site.register(Responde)
admin.site.register(Liga)
admin.site.register(Debate)
